### PR TITLE
Ability to accept extra arguments for ffmpeg.probe command (Issue #187)

### PR DESCRIPTION
**Pull request by akolpakov**
See issue #187

### CODE REVIEW

**Comment by kkroening** [comment]
Looks great. Not sure why CI is failing - probably not related to your PR though. I'll merge once I have time to fix CI.

**Comment by cbitterfield** [comment]
This doesn't seem to be working:

extra = {"sexagesimal":None}

try:
    probe = ffmpeg.probe(FILE,extra)
except ffmpeg.Error as e:
        print(e.stderr, file=sys.stderr)
        sys.exit(1)


Doesn't seem to work; however, it looks like it should

**Comment by akolpakov** [comment]
> This doesn't seem to be working:
> 
> extra = {"sexagesimal":None}
> 
> try:
> probe = ffmpeg.probe(FILE,extra)
> except ffmpeg.Error as e:
> print(e.stderr, file=sys.stderr)
> sys.exit(1)
> 
> Doesn't seem to work; however, it looks like it should

`ffmpeg.probe` accepts params as `**kwargs`. Can you try:

`probe = ffmpeg.probe(FILE, sexagesimal=None)`?

**Comment by 153957** [comment]
`probe = ffmpeg.probe(FILE, **extra)` should also work.

**Comment by akolpakov** [comment]
> `probe = ffmpeg.probe(FILE, **extra)` should also work.

Yes, it is the same. But your example in the previous message is without `**`

Just tested

```
probe = ffmpeg.probe(FILE, sexagesimal=None)
```

It work properly. It shows duration in format `'duration': '0:01:33.994000'`

**Comment by cbitterfield** [comment]
let me check. Got sidetracked on another project.

**Comment by cbitterfield** [comment]
That worked. My programming skills have also improved.  I am starting to get a better understanding of the API.

**Pull request merged**
