### PR TITLE
Add `asplit` filter

### PR DESCRIPTION
**Pull request by Depaulicious**
Add `asplit` filter

### CODE REVIEW

**Comment by kkroening** [comment]
Needs test(s). Looks good otherwise. Will approve once the test is there.

**Comment by kkroening** [comment]
Also let's merge #47 into this so that CI can pass.

**Comment by Depaulicious** [comment]
Oh yeah I forgot tests. I'll add them.

**Comment by Depaulicious** [comment]
Okay, I added tests.

**Pull request merged**
