### PR TITLE
Merry Birthday

### PR DESCRIPTION
**Pull request by lloti**
Maybe a nicer logo for the new year?

### CODE REVIEW

**Comment by Depaulicious** [comment]
I actually love the current logo. Do you have any proposals?

**Comment by Depaulicious** [comment]
Oh it's a PR lol. I like this

**Comment by Depaulicious** [comment]
I like it

**Comment by kkroening** [comment]
Oh man the link went dead. Can you check in the `.png` files and then we can serve them from the git repo?

**Comment by lloti** [comment]
Like this? https://imgur.com/a/S7pt5

**Comment by kkroening** [comment]
> Like this? https://imgur.com/a/S7pt5

Yes - thank you

**Pull request merged**
