### PR TITLE
Cleanup graph source file after rendering graph to pdf

### PR DESCRIPTION
**Pull request by 153957**
Prevent leaving unwanted files.

Uses this option:
https://github.com/xflr6/graphviz/blob/master/graphviz/files.py#L192

### CODE REVIEW

**Comment by 153957** [comment]
Failed CI checks seem to be caused by the outage at Travis, rerunning them should fix that.

**Comment by Depaulicious** [comment]
It looks like it is: https://www.traviscistatus.com/
I don't know how to rerun the build.

Let's wait for @kkroening to review it as he's the owner.

**Comment by kkroening** [comment]
LGTM. Merging.
Thanks!

**Comment by Depaulicious** [comment]
@kkroening did you forget to merge? Should I do it?

**Comment by kkroening** [comment]
Oops, yeah forgot to merge. Merging for real now...

**Pull request merged**
