### PR TITLE
Overwrite output files by default, with option to turn it off

### LINKED ISSUE #34: Run non-interactively
Currently ffmpeg will ask you questions, which freezes the process while it waits for response. That makes it problematic to use on the web.

### PR DESCRIPTION
**Pull request by Depaulicious**
Closes #34

### CODE REVIEW

**Comment by Depaulicious** [comment]
@kkroening I see all CI builds are failing because of the ffmpeg URL thing. Do you want me to rebase it on top of that?

**Comment by noahstier** [comment]
Adding the `None` option makes sense to me as it increases parity with the ffmpeg api. But I would find overwriting by default to be surprising behavior, since ffmpeg's default is not to overwrite.

**Comment by kkroening** [comment]
>  I see all CI builds are failing because of the ffmpeg URL thing. Do you want me to rebase it on top of that?

I merged it into master. CI should be passing now.

**Comment by kkroening** [comment]
Oh crap, I just saw that you made a PR for this after I made the changes. Oops

**Comment by Depaulicious** [comment]
I think you mean #39. Yep that works.

**Pull request closed without merging**
